get http://localhost:9000/books

####
get http://localhost:9000/books/1

####
get http://localhost:9000/books
Content-Type: application/json

{
  "year": 2010,
  "author": "Brandon Sanderson"
}
####
post http://localhost:9000/books
Content-Type: application/json

{
  "title": "The Eye of The World",
  "author": "Robert Jordan",
  "year": 1993,
  "description": "epic fantasy"
}
####
post http://localhost:9000/books
Content-Type: application/json

{
  "title": "Old Testament",
  "author": "Various",
  "year": -165,
  "description": "A holy book of Christianity and Jewish faith"
}
####
post http://localhost:9000/books
Content-Type: application/json

{
  "title": "The Way of Kings",
  "author": "Brandon Sanderson",
  "year": 2010,
  "publisher": "Tor Books",
  "description": "GOAT"
}
####

post http://localhost:9000/books
Content-Type: application/json

{
  "title": "The Words of Radiance",
  "author": "Brandon Sanderson",
  "year": 2014,
  "publisher": "Tor Books",
  "description": "still awesome"
}
#####
post http://localhost:9000/books
Content-Type: application/json

{
  "title": "Oathbringer",
  "author": "Brandon Sanderson",
  "year": 2017,
  "publisher": "Tor Books",
  "description": "!!!"
}

#####

post http://localhost:9000/books
Content-Type: application/json

{
  "title": "The Well of Ascension",
  "author": "Brandon Sanderson",
  "year": 2007,
  "publisher": "Tor Books",
  "description": "Politics in a new world"
}

###
post http://localhost:9000/books
Content-Type: application/json

{
  "title": "Harry Potter and the Philosophers Stone",
  "author": "J.K. Rowling",
  "year": 1997,
  "publisher": "Bloomsbury (UK)",
  "description": "A book about a wizard boy"
}

###

delete http://localhost:9000/books/1