get http://localhost:9000/books

####
get http://localhost:9000/books/1

####
get http://localhost:9000/books
Content-Type: application/json

{
  "year": 2010,
  "author": "Brandon Sanderson"
}

####

post http://localhost:9000/books
Content-Type: application/json

{
  "title": "The Words of Radiance",
  "author": "Brandon Sanderson",
  "year": 2012,
  "publisher": "Tor",
  "description": "still awesome"
}
#####
post http://localhost:9000/books
Content-Type: application/json

{
  "title": "The Way of Kings",
  "author": "Brandon Sanderson",
  "year": 2010,
  "publisher": "Tor",
  "description": "GOAT"
}

#####

post http://localhost:9000/books
Content-Type: application/json

{
  "title": "The Final Empire",
  "author": "Brandon Sanderson",
  "year": 2006,
  "publisher": "Tor Books",
  "description": "Heist novel: What if the Dark Lord won?"
}

###
post http://localhost:9000/books
Content-Type: application/json

{
  "title": "Harry Potter and the Philosophers Stone",
  "author": "J.K. Rowling",
  "year": 1997,
  "publisher": "Bloomsbury (UK)",
  "description": "A book about a wizard boy"
}

###

delete http://localhost:9000/books/3